// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDACofV3RO3t0MD_JT0LJyxXnc9Me-GsQw',
    appId: '1:615116796808:web:1b848c091369315c78403d',
    messagingSenderId: '615116796808',
    projectId: 'chat-app-e5b2d',
    authDomain: 'chat-app-e5b2d.firebaseapp.com',
    storageBucket: 'chat-app-e5b2d.appspot.com',
    measurementId: 'G-QP04D2DWNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhCP-x4RoR4heky5U6sq-Ylzczpre2QX8',
    appId: '1:615116796808:android:d5effc901a34610b78403d',
    messagingSenderId: '615116796808',
    projectId: 'chat-app-e5b2d',
    storageBucket: 'chat-app-e5b2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARTlDFiYrQMpU1SqE2cwsiC3qlNpdDtCI',
    appId: '1:615116796808:ios:9e6c5a3bbe80fbfb78403d',
    messagingSenderId: '615116796808',
    projectId: 'chat-app-e5b2d',
    storageBucket: 'chat-app-e5b2d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARTlDFiYrQMpU1SqE2cwsiC3qlNpdDtCI',
    appId: '1:615116796808:ios:9e6c5a3bbe80fbfb78403d',
    messagingSenderId: '615116796808',
    projectId: 'chat-app-e5b2d',
    storageBucket: 'chat-app-e5b2d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDACofV3RO3t0MD_JT0LJyxXnc9Me-GsQw',
    appId: '1:615116796808:web:da8ac8710e7f3bac78403d',
    messagingSenderId: '615116796808',
    projectId: 'chat-app-e5b2d',
    authDomain: 'chat-app-e5b2d.firebaseapp.com',
    storageBucket: 'chat-app-e5b2d.appspot.com',
    measurementId: 'G-LZEPM2Y4C3',
  );

}